### ISSUE TITLE
我应该怎么pull request自己的代码

### ISSUE THREAD

**Issue by wangyhzzz** [hilen/Alfred.QRCode#1]
我简单按自己的需求修改了一下你的代码(增加使用quick-look 打开图片指令).
但是我不知道如何提交这些代码,因为不知道怎么直接用source里的的东西直接组装成alfredworkflow文件.

**Comment by lanceylai** [comment]
你可以将现有的代码单独测试运行，成功的话直接将源文件 copy 到 workflow 的源文件里（ Workflows--> 右键 --> Show In Finder），然后在 Workflows 界面的 debug 模式下进行调用或调试。开发过程是在 Workflows 的界面里进行的。最后运行 OK 了，可以直接导出 .alfredworkflow 文件
